name: CI

on:
  push:
    branches: ["main"]
  workflow_dispatch:

defaults:
  run:
    working-directory: backend

jobs:
  build_1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm ci
      - run: npm run build --if-present

  deploy_3:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "Run Deploy App"